FROM neo4j:4.3

ENV NEO4J_AUTH=neo4j/letmein \
    APOC_VERSION=4.3.0.0 \
    GRAPHQL_VERSION=3.5.21.5

ENV APOC_URI https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/${APOC_VERSION}/apoc-${APOC_VERSION}-all.jar
RUN sh -c 'cd /var/lib/neo4j/plugins && wget "${APOC_URI}"'

ENV GRAPHQL_URI https://github.com/neo4j-graphql/neo4j-graphql/releases/download/${GRAPHQL_VERSION}/neo4j-graphql-${GRAPHQL_VERSION}.jar
RUN sh -c 'cd /var/lib/neo4j/plugins && wget "${GRAPHQL_URI}"'

EXPOSE 7474 7473 7687

CMD ["neo4j"]
